# Generated by Django 3.2.13 on 2022-05-20 03:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=255, verbose_name='Título')),
                ('post_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data')),
                ('post_content', models.TextField(verbose_name='Conteúdo')),
                ('post_brief', models.TextField(verbose_name='Síntese')),
                ('post_image', models.ImageField(blank=True, null=True, upload_to='post_img/%Y/%m/%d', verbose_name='Imagem')),
                ('post_published', models.BooleanField(default=False, verbose_name='Publicado')),
                ('post_author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('post_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='categorias.category', verbose_name='Categoria')),
            ],
        ),
    ]
